import os

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from notion_client import Client
from dotenv import load_dotenv

load_dotenv()

router = APIRouter()

notion = Client(auth=os.getenv("NOTION_API_KEY"))


class NotionExportRequest(BaseModel):
	meeting_title: str = "Meeting Summary"
	summary: str
	action_items: list[str]
	decisions: list[str]
	open_questions: list[str]


class NotionExportResponse(BaseModel):
	page_url: str
	page_id: str


@router.post("/export/notion", response_model=NotionExportResponse)
async def export_to_notion(body: NotionExportRequest):
	try:
		parent_page_id = os.getenv("NOTION_PARENT_PAGE_ID")
		if parent_page_id is None:
			raise HTTPException(status_code=500, detail="NOTION_PARENT_PAGE_ID not set in .env")

		blocks = []

		blocks.append(
			{
				"object": "block",
				"type": "heading_1",
				"heading_1": {
					"rich_text": [
						{
							"type": "text",
							"text": {"content": body.meeting_title},
						}
					]
				},
			}
		)

		blocks.append(
			{
				"object": "block",
				"type": "heading_2",
				"heading_2": {
					"rich_text": [
						{
							"type": "text",
							"text": {"content": "📋 Summary"},
						}
					]
				},
			}
		)

		blocks.append(
			{
				"object": "block",
				"type": "paragraph",
				"paragraph": {
					"rich_text": [
						{
							"type": "text",
							"text": {"content": body.summary},
						}
					]
				},
			}
		)

		blocks.append({"object": "block", "type": "divider", "divider": {}})

		blocks.append(
			{
				"object": "block",
				"type": "heading_2",
				"heading_2": {
					"rich_text": [
						{
							"type": "text",
							"text": {"content": "✅ Action Items"},
						}
					]
				},
			}
		)

		if body.action_items:
			for item in body.action_items:
				blocks.append(
					{
						"object": "block",
						"type": "bulleted_list_item",
						"bulleted_list_item": {
							"rich_text": [
								{
									"type": "text",
									"text": {"content": item},
								}
							]
						},
					}
				)
		else:
			blocks.append(
				{
					"object": "block",
					"type": "paragraph",
					"paragraph": {
						"rich_text": [
							{
								"type": "text",
								"text": {"content": "No action items identified."},
							}
						]
					},
				}
			)

		blocks.append({"object": "block", "type": "divider", "divider": {}})

		blocks.append(
			{
				"object": "block",
				"type": "heading_2",
				"heading_2": {
					"rich_text": [
						{
							"type": "text",
							"text": {"content": "🏛️ Decisions Made"},
						}
					]
				},
			}
		)

		if body.decisions:
			for item in body.decisions:
				blocks.append(
					{
						"object": "block",
						"type": "bulleted_list_item",
						"bulleted_list_item": {
							"rich_text": [
								{
									"type": "text",
									"text": {"content": item},
								}
							]
						},
					}
				)
		else:
			blocks.append(
				{
					"object": "block",
					"type": "paragraph",
					"paragraph": {
						"rich_text": [
							{
								"type": "text",
								"text": {"content": "No decisions recorded."},
							}
						]
					},
				}
			)

		blocks.append({"object": "block", "type": "divider", "divider": {}})

		blocks.append(
			{
				"object": "block",
				"type": "heading_2",
				"heading_2": {
					"rich_text": [
						{
							"type": "text",
							"text": {"content": "❓ Open Questions"},
						}
					]
				},
			}
		)

		if body.open_questions:
			for item in body.open_questions:
				blocks.append(
					{
						"object": "block",
						"type": "bulleted_list_item",
						"bulleted_list_item": {
							"rich_text": [
								{
									"type": "text",
									"text": {"content": item},
								}
							]
						},
					}
				)
		else:
			blocks.append(
				{
					"object": "block",
					"type": "paragraph",
					"paragraph": {
						"rich_text": [
							{
								"type": "text",
								"text": {"content": "No open questions."},
							}
						]
					},
				}
			)

		blocks.append({"object": "block", "type": "divider", "divider": {}})

		blocks.append(
			{
				"object": "block",
				"type": "paragraph",
				"paragraph": {
					"rich_text": [
						{
							"type": "text",
							"text": {"content": "Generated by MinutelyAI"},
						}
					]
				},
			}
		)

		result = notion.pages.create(
			parent={"page_id": parent_page_id},
			properties={"title": [{"text": {"content": body.meeting_title}}]},
			children=blocks,
		)

		page_id = result["id"]
		page_url = f"https://notion.so/{result['id'].replace('-', '')}"

		return NotionExportResponse(page_url=page_url, page_id=page_id)
	except Exception as e:
		raise HTTPException(status_code=500, detail="Notion export failed: " + str(e))
